name: flash_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  animated_text_kit: ^4.2.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.3
  cloud_firestore: ^4.17.1
  # cloud_firestore: ^4.0.0
  # firebase_auth: ^4.1.0
  # firebase_core: ^2.1.1
  # firebase_core: ^1.10.0  # Update to match firebase-bom version
  # firebase_auth: ^3.1.0  # Update to match firebase-bom version
  # cloud_firestore: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - images/
